target-version = "py312"
line-length = 100

[format]
docstring-code-format = true
line-ending = "lf"

[lint.isort]
force-single-line = true

[lint.pydocstyle]
convention = "google"

[lint]
select = [
  "E4",
  "E7",
  "E9",
  "F",
  "I",
  "N",
  "ARG",
  "A",
  "ASYNC",
  "DTZ",
  "EXE",
  "FA",
  "FLY",
  "G",
  "ICN",
  "LOG",
  "PGH",
  "PLC0414",
  "PLW1510",
  "PLW2901",
  "PYI025",
  "RSE",
  "SIM102",
  "SIM109",
  "SIM112",
  "SIM117",
  "SLOT",
  "T10",
  "YTT",
  "ERA",
  "FURB",
  "Q",
  "S102",
  "S104",
  "S307",
  "S602",
  "S604",
  "S605",
  "S606",
  "S608",
  "S609",
  "S610",
  "S611",
  "S612",
  "S701",
  "PT",
  "UP",
  "B",
  "C4",
  "PIE",
  "RET",
  "PERF",
  "RUF",
]
