[formatting]
align_entries = false
align_comments = false
array_auto_collapse = false
array_auto_expand = true
array_trailing_comma = true
compact_arrays = true
compact_inline_tables = false
reorder_arrays = false
reorder_inline_tables = false
reorder_keys = false
